use_frameworks!

target 'KeyboardSupport_Example' do
  pod 'KeyboardSupport', :path => '../'

  target 'KeyboardSupport_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
