# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.1
language: swift
env:
  global:
    - WORKSPACE=KeyboardSupport.xcworkspace
    - IOS_FRAMEWORK_SCHEME=KeyboardSupport-iOS
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.2,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME" RUN_TESTS="YES" POD_LINT="YES"  RUN_DANGER="YES"
addons:
  homebrew:
    update: true
    taps:
      - danger/tap
    packages:
      - danger-swift
script:
  - swiftlint
  - set -o pipefail

  # Build Framework and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty;
    else
      xcodebuild build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi

  # Run Danger if specified
  - if [ $RUN_DANGER == "YES" ]; then
      danger-swift ci;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
