# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
env:
  global:
    - PROJECT=KeyboardSupport.xcodeproj
    - IOS_FRAMEWORK_SCHEME=KeyboardSupport-iOS
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=11.2,name=iPhone X" SCHEME="$IOS_FRAMEWORK_SCHEME" RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - brew update
  - brew upgrade swiftlint
script:
  - swiftlint
  - set -o pipefail

  # Build Framework and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES | xcpretty;
    else
      xcodebuild build -project "$PROJECT" -scheme "$SCHEME" -destination "$DESTINATION" ONLY_ACTIVE_ARCH=NO | xcpretty;
    fi

  # Run `pod lib lint` if specified
  - if [ $POD_LINT == "YES" ]; then
      pod lib lint;
    fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
